Update 2

diff --git a/install_base b/install_base
--- a/install_base
+++ b/install_base
@@ -1,1 +1,121 @@
 #!/bin/bash
+#-------------------------------------------------------------------------------
+#Created by helmuthdu mailto: helmuthdu[at]gmail[dot]com
+#Modified by M Lenting
+#-------------------------------------------------------------------------------
+#This program is free software: you can redistribute it and/or modify
+#it under the terms of the GNU General Public License as published by
+#the Free Software Foundation, either version 3 of the License, or
+#(at your option) any later version.
+#
+#This program is distributed in the hope that it will be useful,
+#but WITHOUT ANY WARRANTY; without even the implied warranty of
+#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#GNU General Public License for more details.
+#
+#You should have received a copy of the GNU General Public License
+#along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#-------------------------------------------------------------------------------
+# Run this script after your first boot with archlinux (as root)
+if [[ -f `pwd`/sharedfuncs ]]; then
+  source sharedfuncs
+else
+  echo "missing file: sharedfuncs"
+  exit 1
+fi
+
+print_title "https://wiki.archlinux.org/index.php/Arch_Install_Scripts"
+print_info " Martijn likes The Arch Install Scripts are a set of Bash scripts that simplify Arch installation."
+pause_function
+check_boot_system
+check_connection
+check_trim
+pacman -Sy
+while true
+do
+  print_title "ARCHLINUX ULTIMATE INSTALL - https://github.com/helmuthdu/aui"
+  echo " 1) $(mainmenu_item "${checklist[1]}" "Select Keymap")"
+  echo " 2) $(mainmenu_item "${checklist[2]}" "Select Editor")"
+  echo " 3) $(mainmenu_item "${checklist[3]}" "Configure Mirrorlist")"
+  echo " 4) $(mainmenu_item "${checklist[4]}" "Partition Scheme")"
+  echo " 5) $(mainmenu_item "${checklist[5]}" "Install Base System")"
+  echo " 6) $(mainmenu_item "${checklist[6]}" "Configure Fstab")"
+  echo " 7) $(mainmenu_item "${checklist[7]}" "Configure Hostname")"
+  echo " 8) $(mainmenu_item "${checklist[8]}" "Configure Timezone")"
+  echo " 9) $(mainmenu_item "${checklist[9]}" "Configure Hardware Clock")"
+  echo "10) $(mainmenu_item "${checklist[10]}" "Configure Locale")"
+  echo "11) $(mainmenu_item "${checklist[11]}" "Configure Mkinitcpio")"
+  echo "12) $(mainmenu_item "${checklist[12]}" "Install Bootloader")"
+  echo "13) $(mainmenu_item "${checklist[13]}" "Root Password")"
+  echo ""
+  echo " d) Done"
+  echo ""
+  read_input_options
+  for OPT in ${OPTIONS[@]}; do
+    case "$OPT" in
+      1)
+        select_keymap
+        checklist[1]=1
+        ;;
+      2)
+        select_editor
+        checklist[2]=1
+        ;;
+      3)
+        configure_mirrorlist
+        checklist[3]=1
+        ;;
+      4)
+        umount_partitions
+        create_partition_scheme
+        format_partitions
+        checklist[4]=1
+        ;;
+      5)
+        install_base_system
+        configure_keymap
+        checklist[5]=1
+        ;;
+      6)
+        configure_fstab
+        checklist[6]=1
+        ;;
+      7)
+        configure_hostname
+        checklist[7]=1
+        ;;
+      8)
+        configure_timezone
+        checklist[8]=1
+        ;;
+      9)
+        configure_hardwareclock
+        checklist[9]=1
+        ;;
+      10)
+        configure_locale
+        checklist[10]=1
+        ;;
+      11)
+        configure_mkinitcpio
+        checklist[11]=1
+        ;;
+      12)
+        install_bootloader
+        configure_bootloader
+        checklist[12]=1
+        ;;
+      13)
+        root_password
+        checklist[13]=1
+        ;;
+      "d")
+        finish
+        ;;
+      *)
+        invalid_option
+        ;;
+    esac
+  done
+done
+#}}}
